import {
  Flame, Users, Heart, FileText, Star, Shield, Play,
  HandHeart, Globe, ArrowRight, Cross, HelpingHand,
  Activity, Scale, Building2, ShieldCheck, Handshake,
  Phone, Search, Award, Clock, CheckCircle, BarChart3,
  Camera, BookOpen, UserCheck, MapPin, User, Upload,
  TrendingUp, Calendar, Video, Mail, ChevronRight,
  Bookmark, Flower, Quote, X, Maximize2, Download, Share2,
  Briefcase, GraduationCap, Banknote, IndianRupee, LucideIcon,
  Home, Info, Target, Map, Megaphone, Anchor, Tent, MessageSquare,
  Facebook, Twitter, Instagram, Youtube, Linkedin
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  Flame,
  Users,
  Heart,
  FileText,
  Star,
  Shield,
  Play,
  HandHeart,
  Globe,
  ArrowRight,
  Cross,
  HelpingHand,
  Activity,
  Scale,
  Building2,
  ShieldCheck,
  Handshake,
  Phone,
  Search,
  Award,
  Clock,
  CheckCircle,
  BarChart3,
  Camera,
  BookOpen,
  UserCheck,
  MapPin,
  User,
  Upload,
  TrendingUp,
  Calendar,
  Video,
  Mail,
  ChevronRight,
  Bookmark,
  Flower,
  Quote,
  X,
  Maximize2,
  Download,
  Share2,
  Briefcase,
  GraduationCap,
  Banknote,
  IndianRupee,
  Home,
  Info,
  Target,
  Map,
  Megaphone,
  Anchor,
  Tent,
  MessageSquare,
  Facebook,
  Twitter,
  Instagram,
  Youtube,
  Linkedin
};

export const getIcon = (iconName: string): LucideIcon => {
  return iconMap[iconName] || Heart;
};

export default iconMap;